---
title: "Ch_2 A quick tour of traditional NLP"
author: "Samir Gadkari"
date: "3/11/2021"
output: html_document
---

```{r}
library(reticulate)
```

```{python}
import spacy
```

Corpus (plural Corpora): Raw text + metadata related to text.
Tokens: For english, whitespace delimited character groups.
Types: Unique tokens present in a corpus

It is very important to get the right level of tokens to process.
For example the "-ol" in Methanol implies that it is an alcohol.
If you want your neural network to use this information, you
should maybe break the word into Methan and ol?

Lemmas as root forms of the word. ex. fly is a lemma for
flying, flies, flew, flown, etc. To keep dimensionality of the
vector representation low, you should lemmatize your tokens.

Stemming is the poor mans version of lemmatization.
It uses hand-crafted rules to drop the ends of words to
convert them into stems.

```{python}
nlp = spacy.load("en_core_web_sm")

doc = nlp(u"he was running late")
for token in doc:
  print("{} ---> {}".format(token, token.lemma_))

# For some reason, we need a blank line after a line that is
# indented (ex. print line above).
```

## Categorizing sentences and documents

Supervised document classification problems:
  * assigning topic labels to sentences/documents
  * predicting sentiment of reviews
  * filtering spam emails
  * identify language
  * email triaging
Semi-supervised document classification is extremely useful,
but this book will not go into it.

### POS (Part-of-speech) tagging and NER (Named-Entity recognition)

```{python}
nlp = spacy.load("en_core_web_sm")
doc = nlp("Mary slapped the green witch.")
print("Part-of-speech (POS) tagging")
for token in doc:
  print("{} - {}".format(token, token.pos_))
print()

print("Shallow-parsing - generates higher-order units composed of "
      "noun, verb, etc.")
for chunk in doc.noun_chunks:
  print("{} - {}".format(chunk, chunk.label_))

```

The named entity is also very useful. It mentions a person name, location name,
organization name, etc.

### Identifying relationships between grammatical atoms in sentences

Dependency parsing shows the grammatical relationships between parts of a
sentence.

### Word senses and semantics

The different meanings of a word are it's senses.
Wordnet aims to capture all the meanings of each word.
